contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #wutest channel"
    url: https://nfcore.slack.com/channels/wutest
    about: Discussion about the nf-core/wutest pipeline
